### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by theseusyang** [webschik/ng2react-builder#3]
Hi ,

How to run this project to translate angular template file to react js file?

**Comment by webschik** [comment]
Hi,

There is an example in README - https://github.com/webschik/ng2react-builder#usage
`ng2react-builder` module exports [transform](https://github.com/webschik/ng2react-builder#transform) function which takes a map of options.

`options. components` is an array of options for components to compile
`options.components[i].template` is a string with Angular 1 code (can be provided e.g. by fs.readFile) which will be transpired to JSX code.

Check other options to add more granular configuration to the compilation process.

Also, you may find more samples in the `__tests__` folder, e.g. `__tests__/component6/test.spec.ts`
