### ISSUE TITLE
Some angular 1 codes  can't translate to react, how to add these functions to ng2react-builder?

### ISSUE THREAD

**Issue by theseusyang** [webschik/ng2react-builder#4]
Hi,

I find some ng ui function can't translate to react, like ng-init...,  how to add  related translating codes into ng2react-builder?

**Comment by webschik** [comment]
Hi,

transpiling of `ng-init` is not implemented.

This module can transpile the next built-in directives:
* ng-if, ng-show, ng-hide
* ng-repeat, ng-repeat-start, ng-repeat-end
* ng-bind
* ng-cloak, ng-trim, ng-app will be ignored

More in https://github.com/webschik/ng2react-builder/blob/2a79aa0c2b276b87f8e729025bea84eb1558bace/src/parser/parse-ng-attrs.ts#L27

You may configure how to transpile custom or built-in directives to React elements (via `directivesToTags`) or to text nodes (via `directivesToTextNodes`), see samples in docs and tests.
